export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CREATE_HW_PROFILE_START = "CREATE_HW_PROFILE_START";
export const CREATE_HW_PROFILE_SUCCESS = "CREATE_HW_PROFILE_SUCCESS";
export const CREATE_HW_PROFILE_FAIL = "CREATE_HW_PROFILE_FAIL";
export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";
export const CHECK_PATIENT_IMAGE_UPLOAD = "CHECK_PATIENT_IMAGE_UPLOAD";
export const RESET_PATIENT_IMAGE_UPLOAD = "RESET_PATIENT_IMAGE_UPLOAD";

export const SWITCH_USER_TYPE_TO_PATIENT = "SWITCH_USER_TYPE_TO_PATIENT";
export const SWITCH_USER_TYPE_TO_HW = "SWITCH_USER_TYPE_TO_HW";
export const PATIENT_USER_MODE = "PATIENT_USER_MODE";
export const HW_USER_MODE = "HW_USER_MODE";

export const GET_PATIENTS_START = "GET_PATIENTS_START";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";
export const GET_PATIENTS_BY_GENDER = "GET_PATIENTS_BY_GENDER";
export const GET_PATIENTS_BY_AGE = "GET_PATIENTS_BY_AGE";
export const GET_PATIENTS_BY_BMI = "GET_PATIENTS_BY_BMI";
export const GET_PATIENTS_BY_NAME = "GET_PATIENTS_BY_NAME";
export const GET_PATIENT = "GET_PATIENT";

export const GET_HW_START = "GET_HW_START";
export const GET_HW_SUCCESS = "GET_HW_SUCCESS";
export const GET_HW_FAIL = "GET_HW_FAIL";

export const SAVE_ENCOUNTER_START = "SAVE_ENCOUNTER_START";
export const SAVE_ENCOUNTER_SUCCESS = "SAVE_ENCOUNTER_SUCCESS";
export const SAVE_ENCOUNTER_FAIL = "SAVE_ENCOUNTER_FAIL";
export const SEND_ENCOUNTER_START = "SEND_ENCOUNTER_START";
export const SEND_ENCOUNTER_SUCCESS = "SEND_ENCOUNTER_SUCCESS";
export const SEND_ENCOUNTER_FAIL = "SEND_ENCOUNTER_FAIL";
export const SET_RECEIVERS = "SET_RECEIVERS";
export const SET_ENCOUNTER_SENT_STATUS = "SET_ENCOUNTER_SENT_STATUS";

export const FETCH_ENCOUNTERS_START = "FETCH_ENCOUNTERS_START";
export const FETCH_ENCOUNTERS_SUCCESS = "FETCH_ENCUNTERS_SUCCESS";
export const FETCH_ENCOUNTERS_FAIL = "FETCH_ENCOUNTERS_FAIL";

export const TOGGLE_FILTER_CONTROLS = "SHOW_FILTER_CONTROLS";
export const HIDE_FILTER_CONTROLS = "HIDE_FILTER_CONTROLS";

export const RUN_MESSENGER_START = "RUN_MESSENGER_START";
export const RUN_MESSENGER_SUCCESS = "RUN_MESSENGER_SUCCESS";
export const RUN_MESSENGER_FAIL = "RUN_MESSENGER_FAIL";
export const CHAT_WITH_A_PATIENT = "CHAT_WITH_A_PATIENT";
