export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CREATE_HW_PROFILE_START = "CREATE_HW_PROFILE_START";
export const CREATE_HW_PROFILE_SUCCESS = "CREATE_HW_PROFILE_SUCCESS";
export const CREATE_HW_PROFILE_FAIL = "CREATE_HW_PROFILE_FAIL";
export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";
export const CHECK_PATIENT_IMAGE_UPLOAD = "CHECK_PATIENT_IMAGE_UPLOAD";
export const RESET_PATIENT_IMAGE_UPLOAD = "RESET_PATIENT_IMAGE_UPLOAD";

export const SWITCH_USER_TYPE = "SWITCH_USER_TYPE";

export const GET_PATIENTS = "GET_PATIENTS";
