export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const CREATE_HW_PROFILE_START = "CREATE_HW_PROFILE_START";
export const CREATE_HW_PROFILE_SUCCESS = "CREATE_HW_PROFILE_SUCCESS";
export const CREATE_HW_PROFILE_FAIL = "CREATE_HW_PROFILE_FAIL";
export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";
export const CHECK_PATIENT_IMAGE_UPLOAD = "CHECK_PATIENT_IMAGE_UPLOAD";
export const RESET_PATIENT_IMAGE_UPLOAD = "RESET_PATIENT_IMAGE_UPLOAD";

export const SWITCH_USER_TYPE = "SWITCH_USER_TYPE";
export const PATIENT_USER_MODE = "PATIENT_USER_MODE";
export const HW_USER_MODE = "HW_USER_MODE";

export const GET_PATIENTS_START = "GET_PATIENTS_START";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";
export const GET_PATIENTS_BY_GENDER = "GET_PATIENTS_BY_GENDER";
export const GET_PATIENTS_BY_AGE = "GET_PATIENTS_BY_AGE";
export const GET_PATIENTS_BY_BMI = "GET_PATIENTS_BY_BMI";
export const GET_PATIENTS_BY_NAME = "GET_PATIENTS_BY_NAME";
export const GET_PATIENT = "GET_PATIENT";

export const TOGGLE_FILTER_CONTROLS = "SHOW_FILTER_CONTROLS";
export const HIDE_FILTER_CONTROLS = "HIDE_FILTER_CONTROLS";
